<?php
include "Form.html";
echo "<br><br><fieldset>";
echo "<fieldset>";
echo "<legend> Rincian Pendaftaran:</legend><br>";
echo "Nama:";
echo $_GET["namaD"];
echo " ";
echo $_GET["namaB"];
echo "<br>";
echo "Email:";
echo $_GET["email"];
echo "<br>";
echo "Jenis Kelamin:";
echo $_GET["jk"];
echo "<br>";
echo "Negara:";
echo $_GET["negara"];
echo "<br>";
echo "<p><span>Pembuatan akun Telah Berhasil!!</span><p>";
echo "</fieldset>";
echo "</fieldset>";
